monolog:
    channels:
        - traffic_cloak
    handlers:
        main:
            type: rotating_file
            path: "%kernel.logs_dir%/app.log"
            level: info
            max_files: 10
            channels: ["!event"]
        
        traffic_cloak:
            type: rotating_file
            path: "%kernel.logs_dir%/traffic_cloak.log"
            level: debug
            max_files: 10
            channels: ["traffic_cloak"]
        
        console:
            type: console
            process_psr_3_messages: false
            channels: ["!event", "!doctrine", "!console"]

when@dev:
    monolog:
        handlers:
            main:
                type: stream
                path: "%kernel.logs_dir%/dev.log"
                level: debug
                channels: ["!event"]
            
            traffic_cloak:
                type: stream
                path: "%kernel.logs_dir%/traffic_cloak_dev.log"
                level: debug
                channels: ["traffic_cloak"]

when@test:
    monolog:
        handlers:
            main:
                type: "null"
                processing: false
            nested:
                type: stream
                path: "%kernel.logs_dir%/%kernel.environment%.log"
                level: debug

when@prod:
    monolog:
        handlers:
            main:
                type: fingers_crossed
                action_level: error
                handler: nested
                excluded_http_codes: [404, 405]
                buffer_size: 50 # How many messages should be saved? Prevent memory leaks
            nested:
                type: stream
                path: php://stderr
                level: debug
                formatter: monolog.formatter.json
            console:
                type: console
                process_psr_3_messages: false
                channels: ["!event", "!doctrine"]
            deprecation:
                type: stream
                channels: [deprecation]
                path: php://stderr
                formatter: monolog.formatter.json
