version: "3.9"
services:
  app:
    platform: linux/amd64
    image: php:8.3-cli
    working_dir: /app
    volumes:
      - .:/app
      - ./docker/php.ini:/usr/local/etc/php/php.ini
    command: |
      sh -c '
        docker-php-ext-install pcntl && 
        php -S 0.0.0.0:8000 -t public
      '
    environment:
      - APP_ENV=dev
    depends_on:
      - selenium
    networks:
      - symfony_network

  composer:
    platform: linux/arm64
    image: composer:2
    container_name: composer
    working_dir: /app
    volumes:
      - .:/app
    networks:
      - symfony_network
    entrypoint: ["composer"]

  selenium:
    platform: linux/arm64
    image: seleniarm/standalone-chromium:latest
    container_name: selenium
    ports:
      - "4444:4444"
    networks:
      - symfony_network

networks:
  symfony_network:
    driver: bridge