parameters:
    env(DOH_ENDPOINT): 'https://dns.google/resolve'

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    App\Command\DnsLookupCommand:
        arguments:
            $dataDir: '%kernel.project_dir%/data'
        tags:
            - { name: 'console.command' }

    App\Handler\Dns\DnsOverHttpsResolver:
        arguments:
            $endpoint: '%env(string:DOH_ENDPOINT)%'

    App\Service\DomainLookupService:
        arguments:
            $logger: '@logger'
            App\Contract\DnsResolverInterface: '@App\Handler\Dns\DnsOverHttpsResolver'


